app/memory_cache/forms/user.py
from flask_wtf import FlaskForm
from flask_wtf.file import FileField, FileRequired, FileAllowed
from wtforms import StringField, TextAreaField, BooleanField, SubmitField, HiddenField, PasswordField
from wtforms.validators import DataRequired, Length, Regexp, Optional, URL, EqualTo, ValidationError, Email
from flask_login import current_user

from memory_cache.models import User


class EditProfileForm(FlaskForm):
    name = StringField('Name', validators=[DataRequired(), Length(1, 30)])
    username = StringField('Username', validators=[DataRequired(), Length(1, 20),
                                                   Regexp('^[a-zA-Z0-9]*$',
                                                          message='The username should contain only a-z, A-Z, 0-9.')])
    website = StringField('Website', validators=[Optional(), URL(), Length(0, 254)])
    bio = TextAreaField('Bio', validators=[Optional(), Length(0, 120)])
    location = StringField('Location', validators=[Optional(), Length(0, 30)])
    submit = SubmitField()

    def validate_username(self, field):
        if field.data != current_user.username and User.query.filter(User.username == field.data).first():
            raise ValidationError('The username is already in use.')


class UploadAvatarForm(FlaskForm):
    image = FileField('Upload (<=3Mb)', validators=[
        FileRequired(), FileAllowed(['jpg', 'png'], message='The file format should be .jpg or.png.')
    ])
    submit = SubmitField('Upload')


class CropAvatarForm(FlaskForm):
    x = HiddenField()
    y = HiddenField()
    w = HiddenField()
    h = HiddenField()
    submit = SubmitField('Crop and Update')


class NotificationSettingForm(FlaskForm):
    receive_comment_notification = BooleanField('New comment')
    receive_follow_notification = BooleanField('New Follower')
    receive_collect_notification = BooleanField('New Collector')
    submit = SubmitField()


class PrivacySettingForm(FlaskForm):
    public_collections = BooleanField('Public my collections')
    submit = SubmitField()


class ChangePasswordForm(FlaskForm):
    old_password = PasswordField('Old password', validators=[DataRequired(), Length(6, 128)])
    password = PasswordField('New password', validators=[DataRequired(), Length(6, 128), EqualTo('password2')])
    password2 = PasswordField('Confirm password', validators=[DataRequired()])
    submit = SubmitField()


class ChangeEmailForm(FlaskForm):
    email = StringField('New email', validators=[DataRequired(), Length(1, 254), Email()])
    submit = SubmitField()

    def validate_email(self, field):
        if User.query.filter(User.email == field.data).first():
            raise ValidationError('The email is already in use.')


class DeleteAccountForm(FlaskForm):
    username = StringField('Username', validators=[DataRequired(), Length(1, 20)])
    submit = SubmitField()

    def validate_username(self, field):
        if field.data != current_user.username:
            raise ValidationError('Wrong username.')

app/memory_cache/blueprints/user.py
from flask import Blueprint, request, current_app, render_template, flash, redirect, url_for
from flask_login import login_required, current_user, fresh_login_required, logout_user

from memory_cache.decorators import confirm_required, permission_required
from memory_cache.extensions import db, avatars
from memory_cache.forms.user import EditProfileForm, UploadAvatarForm, CropAvatarForm, ChangePasswordForm, \
    NotificationSettingForm, PrivacySettingForm, DeleteAccountForm, ChangeEmailForm
from memory_cache.models import User, Photo, Collect, Follow
from memory_cache.notifications import push_follow_notification
from memory_cache.utils import redirect_back, flash_errors, generate_token, validate_token
from memory_cache.emails import send_change_email_email
from memory_cache.settings import Operations

user_bp = Blueprint('user', __name__)


@user_bp.route('/<username>')
def index(username):
    user = User.query.filter(User.username == username).first_or_404()
    if user == current_user and user.locked:
        flash('Your account is locked.', 'danger')
    if user == current_user and not user.active:
        logout_user()
    page = request.args.get('page', 1, type=int)
    per_page = current_app.config['APP_PHOTO_PER_PAGE']
    pagination = Photo.query.with_parent(user).order_by(Photo.timestamp.desc()).paginate(page, per_page)
    photos = pagination.items
    return render_template('user/index.html', user=user, pagination=pagination, photos=photos)


@user_bp.route('/<username>/collections')
def show_collections(username):
    user = User.query.filter(User.username == username).first_or_404()
    page = request.args.get('page', 1, type=int)
    per_page = current_app.config['APP_PHOTO_PER_PAGE']
    pagination = Collect.query.with_parent(user).order_by(Collect.timestamp.desc()).paginate(page, per_page)
    collects = pagination.items
    return render_template('user/collections.html', user=user, pagination=pagination, collects=collects)


@user_bp.route('/follow/<username>', methods=['POST'])
@login_required
@confirm_required
@permission_required('FOLLOW')
def follow(username):
    user = User.query.filter_by(username=username).first_or_404()
    if current_user.is_following(user):
        flash('Already followed.', 'info')
        return redirect_back()

    current_user.follow(user)
    flash('User followed.', 'success')
    if user.author.receive_follow_notification:
        push_follow_notification(follower=current_user, receiver=user)
    return redirect_back()


@user_bp.route('/unfollow/<username>', methods=['POST'])
@login_required
@confirm_required
@permission_required('FOLLOW')
def unfollow(username):
    user = User.query.filter_by(username=username).first_or_404()
    if not current_user.is_following(user):
        flash('Not follow yet.', 'info')
        return redirect_back()

    current_user.unfollow(user)
    flash('User unfollowed.', 'success')
    return redirect_back()


@user_bp.route('/<username>/followers')
def show_followers(username):
    user = User.query.filter(User.username == username).first_or_404()
    page = request.args.get('page', 1, type=int)
    per_page = current_app.config['APP_USER_PER_PAGE']
    pagination = user.followers.order_by(Follow.timestamp.desc()).paginate(page, per_page)
    follows = pagination.items
    return render_template('user/followers.html', user=user, pagination=pagination, follows=follows)


@user_bp.route('/<username>/following')
def show_following(username):
    user = User.query.filter(User.username == username).first_or_404()
    page = request.args.get('page', 1, type=int)
    per_page = current_app.config['APP_USER_PER_PAGE']
    pagination = user.following.order_by(Follow.timestamp.desc()).paginate(page, per_page)
    follows = pagination.items
    return render_template('user/following.html', user=user, pagination=pagination, follows=follows)


@user_bp.route('/settings/profile', methods=['GET', 'POST'])
@login_required
def edit_profile():
    form = EditProfileForm()

    if form.validate_on_submit():
        current_user.name = form.name.data
        current_user.username = form.username.data
        current_user.website = form.website.data
        current_user.bio = form.bio.data
        current_user.location = form.location.data
        db.session.commit()
        flash('Profile updated.', 'success')
        return redirect(url_for('user.edit_profile'))
    form.name.data = current_user.name
    form.username.data = current_user.username
    form.website.data = current_user.website
    form.bio.data = current_user.bio
    form.location.data = current_user.location
    return render_template('user/settings/edit_profile.html', form=form)


@user_bp.route('/settings/avatar', methods=['GET', 'POST'])
@login_required
@confirm_required
def change_avatar():
    upload_form = UploadAvatarForm()
    crop_form = CropAvatarForm()
    return render_template('user/settings/change_avatar.html', upload_form=upload_form, crop_form=crop_form)


@user_bp.route('/settings/avatar/upload', methods=['POST'])
@login_required
@confirm_required
def upload_avatar():
    form = UploadAvatarForm()
    if form.validate_on_submit():
        image = form.image.data
        filename = avatars.save_avatar(image)  # 保存头像文件，返回文件名
        current_user.avatar_raw = filename
        db.session.commit()
        flash('Image uploaded, please crop.', 'success')
    flash_errors(form)
    return redirect(url_for('user.change_avatar'))


@user_bp.route('/settings/avatar/crop', methods=['POST'])
@login_required
@confirm_required
def crop_avatar():
    form = CropAvatarForm()
    if form.validate_on_submit():
        x = form.x.data
        y = form.y.data
        w = form.w.data
        h = form.h.data
        filenames = avatars.crop_avatar(current_user.avatar_raw, x, y, w, h)
        current_user.avatar_s = filenames[0]
        current_user.avatar_m = filenames[1]
        current_user.avatar_l = filenames[2]
        db.session.commit()
        flash('Avatar updated.', 'success')
    flash_errors(form)
    return redirect(url_for('user.change_avatar'))


@user_bp.route('/settings/change-password', methods=['GET', 'POST'])
@fresh_login_required
def change_password():
    form = ChangePasswordForm()
    if form.validate_on_submit():
        if current_user.validate_password(form.old_password.data):
            current_user.set_password(form.password.data)
            db.session.commit()
            flash('Password updated.', 'success')
            return redirect(url_for('.index', username=current_user.username))
        else:
            flash('Old password is incorrect.', 'warning')
    return render_template('user/settings/change_password.html', form=form)


@user_bp.route('/settings/notifications', methods=['GET', 'POST'])
@login_required
def notification_setting():
    form = NotificationSettingForm()
    if form.validate_on_submit():
        current_user.receive_comment_notification = form.receive_comment_notification.data
        current_user.receive_follow_notification = form.receive_follow_notification.data
        current_user.receive_collect_notification = form.receive_collect_notification.data
        db.session.commit()
        flash('Notification settings updated.', 'success')
        return redirect(url_for('user.index', username=current_user.username))
    form.receive_comment_notification.data = current_user.receive_comment_notification
    form.receive_follow_notification.data = current_user.receive_follow_notification
    form.receive_collect_notification.data = current_user.receive_collect_notification
    return render_template('user/settings/edit_notification.html', form=form)


@user_bp.route('/settings/privacy', methods=['GET', 'POST'])
@login_required
def privacy_setting():
    form = PrivacySettingForm()
    if form.validate_on_submit():
        current_user.public_collections = form.public_collections.data
        db.session.commit()
        flash('Privacy settings updated.', 'success')
        return redirect(url_for('user.index', username=current_user.username))
    form.public_collections.data = current_user.public_collections
    return render_template('user/settings/edit_privacy.html', form=form)


@user_bp.route('/settings/delete-account', methods=['GET', 'POST'])
@fresh_login_required
def delete_account():
    form = DeleteAccountForm()
    if form.validate_on_submit():
        db.session.delete(current_user._get_current_object())
        db.session.commit()
        flash('Account deleted permanently, goodbye!', 'success')
        return redirect(url_for('main.index'))
    return render_template('user/settings/delete_account.html', form=form)

@user_bp.route('/settings/change-email', methods=['GET', 'POST'])
@fresh_login_required
def change_email_request():
    form = ChangeEmailForm()
    if form.validate_on_submit():
        new_email = form.email.data.lower()
        token = generate_token(user=current_user, operation=Operations.CHANGE_EMAIL, new_email=new_email)
        send_change_email_email(user=current_user, token=token, to=new_email)
        flash('Confirm email sent, check your inbox.', 'info')
        return redirect(url_for('user.index', username=current_user.username))
    return render_template('user/settings/change_email.html', form=form)


@user_bp.route('/change-email/confirm/<token>')
@login_required
def change_email(token):
    if validate_token(user=current_user, token=token, operation=Operations.CHANGE_EMAIL):
        flash('Email updated.', 'success')
        return redirect(url_for('user.index', username=current_user.username))
    else:
        flash('Invalid or expired token.', 'warning')
        return redirect(url_for('user.change_email_request'))

app/memory_cache/templates/user/settings/base.html
{% extends 'base.html' %}
{% from 'bootstrap/form.html' import render_form %}
{% from 'bootstrap/nav.html' import render_nav_item %}

{% block content %}
<div class="page-header">
    <h1>Settings</h1>
</div>
<div class="row">
    <div class="col-md-3">
        <div class="nav nav-pills flex-column" role="tablist" aria-orientation="vertical">
            {{ render_nav_item('user.edit_profile', 'Edite Profile') }}
            {{ render_nav_item('user.change_avatar', 'Change Avatar') }}
            {{ render_nav_item('user.change_password', 'Change Password') }}
            {{ render_nav_item('user.change_email_request', 'Change Email') }}
            {{ render_nav_item('user.notification_setting', 'Notification') }}
            {{ render_nav_item('user.privacy_setting', 'Privacy') }}
            {{ render_nav_item('user.delete_account', 'Delete Account') }}
        </div>
    </div>
    <div class="col-md-9">
        {% block setting_content %}{% endblock %}
    </div>
</div>
{% endblock %}

app/memory_cache/templates/user/settings/change_avatar.html
{% extends 'user/settings/base.html' %}
{% from 'bootstrap/form.html' import render_form %}

{% block title %}Change Avatar{% endblock %}

{% block styles %}
{{ super() }}
<link rel="stylesheet" href="{{ url_for('static', filename='jcrop/css/jquery.Jcrop.min.css') }}">
{% endblock %}

{% block setting_content %}
    <div class="card w-100 bg-light">
        <h3 class="card-header">Change Avatar</h3>
        <div class="card-body">
            {{ render_form(upload_form, action=url_for('user.upload_avatar')) }}
            <small class="text-muted">
                Your file's size must be less than 3MB, the allowed formats are png and jpg.
            </small>
            <hr>
            {{ avatars.crop_box('main.get_avatar', current_user.avatar_raw) }}
            {{ avatars.preview_box('main.get_avatar', current_user.avatar_raw) }}
            <hr>
            {{ render_form(crop_form, action=url_for('user.crop_avatar')) }}
        </div>
    </div>
{% endblock %}

{% block scripts %}
{{ super() }}
<script src="{{ url_for('static', filename='jcrop/js/jquery.Jcrop.min.js') }}"></script>
{{ avatars.init_jcrop() }}
{% endblock %}

app/memory_cache/templates/user/settings/change_email.html
{% extends 'user/settings/base.html' %}
{% from 'bootstrap/form.html' import render_form %}

{% block title %}Change Email{% endblock %}

{% block setting_content %}
    <div class="card w-100 bg-light">
        <h3 class="card-header">Change Email</h3>
        <div class="card-body">
            {{ render_form(form) }}
        </div>
    </div>
{% endblock %}

app/memory_cache/templates/user/settings/change_password.html
{% extends 'user/settings/base.html' %}
{% from 'bootstrap/form.html' import render_form %}

{% block title %}Change Password{% endblock %}

{% block setting_content %}
    <div class="card w-100 bg-light">
        <h3 class="card-header">Change Password</h3>
        <div class="card-body">
            {{ render_form(form) }}
        </div>
    </div>
{% endblock %}

app/memory_cache/templates/user/settings/delete_account.html
{% extends 'user/settings/base.html' %}
{% from 'bootstrap/form.html' import render_form %}

{% block title %}Delete Account{% endblock %}

{% block setting_content %}
    <div class="card w-100 bg-light">
        <h3 class="card-header">Delete Account</h3>
        <div class="card-body">
            {{ render_form(form) }}
        </div>
    </div>
{% endblock %}

app/memory_cache/templates/user/settings/edit_notification.html
{% extends 'user/settings/base.html' %}
{% from 'bootstrap/form.html' import render_form %}

{% block title %}Edit Notification{% endblock %}

{% block setting_content %}
    <div class="card w-100 bg-light">
        <h3 class="card-header">Edit Notification</h3>
        <div class="card-body">
            {{ render_form(form) }}
        </div>
    </div>
{% endblock %}

app/memory_cache/templates/user/settings/edit_privacy.html
{% extends 'user/settings/base.html' %}
{% from 'bootstrap/form.html' import render_form %}

{% block title %}Edit Privacy{% endblock %}

{% block setting_content %}
    <div class="card w-100 bg-light">
        <h3 class="card-header">Edit Privacy</h3>
        <div class="card-body">
            {{ render_form(form) }}
        </div>
    </div>
{% endblock %}

app/memory_cache/templates/user/settings/edit_profile.html
{% extends 'user/settings/base.html' %}
{% from 'bootstrap/form.html' import render_form %}

{% block title %}Edit Profile{% endblock %}

{% block setting_content %}
    <div class="card w-100 bg-light">
        <h3 class="card-header">Edit Profile</h3>
        <div class="card-body">
            {{ render_form(form) }}
        </div>
    </div>
{% endblock %}