app/memory_cache/forms/main.py
from flask_wtf import FlaskForm
from wtforms import TextAreaField, SubmitField, StringField
from wtforms.validators import DataRequired, Length, Optional


class DescriptionForm(FlaskForm):
    description = TextAreaField('Description', validators=[Optional(), Length(0, 500)])
    submit = SubmitField()


class TagForm(FlaskForm):
    tag = StringField('Add Tag (use space to separate)', validators=[Optional(), Length(0, 64)])
    submit = SubmitField()


class CommentForm(FlaskForm):
    body = TextAreaField('Comment', validators=[DataRequired()])
    submit = SubmitField()

app/memory_cache/blueprints/ajax.py
from flask import Blueprint, render_template, jsonify
from flask_login import current_user

from memory_cache.models import User, Notification, Photo
from memory_cache.notifications import push_follow_notification, push_collect_notification

ajax_bp = Blueprint('ajax', __name__)


@ajax_bp.route('/profile/<int:user_id>')
def get_profile(user_id):
    user = User.query.get_or_404(user_id)
    return render_template('main/profile_popup.html', user=user)


@ajax_bp.route('/follow/<username>', methods=['POST'])
def follow(username):
    if not current_user.is_authenticated:  # 验证登录状态
        return jsonify(message='Login required.'), 403
    if not current_user.confirmed:  # 验证账号确认状态
        return jsonify(message='Confirmed account required.'), 400
    if not current_user.can('FOLLOW'):  # 验证账号关注权限状态
        return jsonify(message='No permission.'), 403

    user = User.query.filter_by(username=username).first_or_404()
    if current_user.is_following(user):
        return jsonify(message='Already followed.'), 400

    current_user.follow(user)
    if user.receive_follow_notification:
        push_follow_notification(follower=current_user, receiver=user)
    return jsonify(message='User followed')


@ajax_bp.route('/unfollow/<username>', methods=['POST'])
def unfollow(username):
    if not current_user.is_authenticated:  # 验证登录状态
        return jsonify(message='Login required.'), 403

    user = User.query.filter_by(username=username).first_or_404()
    if not current_user.is_following(user):
        return jsonify(message='Not follow yet.'), 400

    current_user.unfollow(user)
    return jsonify(message='Follow canceled.')


@ajax_bp.route('/followers-count/<int:user_id>')
def followers_count(user_id):
    user = User.query.get_or_404(user_id)
    count = user.followers.count() - 1  # 减去自己
    return jsonify(count=count)


@ajax_bp.route('/notifications-count')
def notifications_count():
    if not current_user.is_authenticated:
        return jsonify(message='Login required.'), 403

    count = Notification.query.with_parent(current_user).filter_by(is_read=False).count()  # 减去自己
    return jsonify(count=count)


@ajax_bp.route('/collect/<int:photo_id>', methods=['POST'])
def collect(photo_id):
    if not current_user.is_authenticated:  # 验证登录状态
        return jsonify(message='Login required.'), 403
    if not current_user.confirmed:  # 验证账号确认状态
        return jsonify(message='Confirmed account required.'), 400
    if not current_user.can('COLLECT'):  # 验证账号关注权限状态
        return jsonify(message='No permission.'), 403

    photo = Photo.query.get_or_404(photo_id)
    if current_user.is_collecting(photo):
        return jsonify(message='Already collected.'), 400

    current_user.collect(photo)
    if photo.author.receive_collect_notification and current_user != photo.author:
        push_collect_notification(collector=current_user, photo_id=photo_id, receiver=photo.author)
    return jsonify(message='User collected')


@ajax_bp.route('/uncollect/<int:photo_id>', methods=['POST'])
def uncollect(photo_id):
    if not current_user.is_authenticated:  # 验证登录状态
        return jsonify(message='Login required.'), 403

    photo = Photo.query.get_or_404(photo_id)
    if not current_user.is_collecting(photo):
        return jsonify(message='Not collect yet.'), 400

    current_user.uncollect(photo)
    return jsonify(message='Collect canceled.')


@ajax_bp.route('/collecters-count/<int:photo_id>')
def collectors_count(photo_id):
    photo = Photo.query.get_or_404(photo_id)
    count = photo.collectors.count()
    return jsonify(count=count)

app/memory_cache/blueprints/main.py
import os

from flask import Blueprint, render_template, request, current_app, send_from_directory, flash, redirect, url_for, abort
from flask_dropzone import random_filename
from flask_login import current_user
from flask_login import login_required
from sqlalchemy.sql.expression import func

from memory_cache.decorators import permission_required, confirm_required
from memory_cache.extensions import db
from memory_cache.forms.main import DescriptionForm, TagForm, CommentForm
from memory_cache.models import Photo, Tag, Comment, Collect, Notification, Follow, User
from memory_cache.notifications import push_collect_notification, push_comment_notification
from memory_cache.utils import resize_image, flash_errors, redirect_back

main_bp = Blueprint('main', __name__)


@main_bp.route('/')
def index():
    if current_user.is_authenticated:
        tags = Tag.query.join(Tag.photos).group_by(Tag.id).order_by(func.count(Photo.id).desc()).limit(10)

        followed_photos = Photo.query.join(Follow, Follow.followed_id == Photo.author_id).filter(
            Follow.follower_id == current_user.id).order_by(Photo.timestamp.desc())
        page = request.args.get('page', 1, type=int)
        per_page = current_app.config['APP_PHOTO_PER_PAGE']
        pagination = followed_photos.paginate(page, per_page)
        photos = pagination.items
    else:
        pagination = None
        photos = None
        tags = None
    return render_template('main/index.html', pagination=pagination, photos=photos, tags=tags)


@main_bp.route('/explore')
def explore():
    photos = Photo.query.order_by(func.random()).limit(12)
    return render_template('main/explore.html', photos=photos)


@main_bp.route('/search')
def search():
    q =request.args.get('q', '')
    if q == '':
        flash('Enter keyword about photo, user or tag.', 'warning')
        return redirect_back()

    category = request.args.get('category', 'photo')
    page = request.args.get('page', 1, type=int)
    per_page = current_app.config['APP_SEARCH_RESULT_PER_PAGE']
    if category == 'photo':
        pagination = Photo.query.whooshee_search(q).paginate(page, per_page)
    elif category == 'tag':
        pagination = Tag.query.whooshee_search(q).paginate(page, per_page)
    else:
        pagination = User.query.whooshee_search(q).paginate(page, per_page)
    results = pagination.items
    return render_template('main/search.html', q=q, pagination=pagination, results=results, category=category)


@main_bp.route('/upload', methods=['GET', 'POST'])
@login_required
@confirm_required
@permission_required('UPLOAD')
def upload():
    if request.method == 'POST' and 'file' in request.files:
        f = request.files.get('file')
        filename = random_filename(f.filename)
        f.save(os.path.join(current_app.config['APP_UPLOAD_PATH'], filename))
        filename_s = resize_image(f, filename, 400)
        filename_m = resize_image(f, filename, 800)
        photo = Photo(
            filename=filename,
            filename_s=filename_s,
            filename_m=filename_m,
            author=current_user._get_current_object()
        )
        db.session.add(photo)
        db.session.commit()
    return render_template('main/upload.html')


@main_bp.route('/avatars/<path:filename>')
def get_avatar(filename):
    return send_from_directory(current_app.config['AVATARS_SAVE_PATH'], filename)


@main_bp.route('/uploads/<path:filename>')
def get_image(filename):
    return send_from_directory(current_app.config['APP_UPLOAD_PATH'], filename)


@main_bp.route('/photo/<int:photo_id>', methods=['GET', 'POST'])
def show_photo(photo_id):
    photo = Photo.query.get_or_404(photo_id)

    page = request.args.get('page', 1, type=int)
    per_page = current_app.config['APP_COMMENT_PER_PAGE']
    pagination = Comment.query.with_parent(photo).order_by(Comment.timestamp.desc()).paginate(page, per_page)
    comments = pagination.items

    comment_form = CommentForm()
    description_form = DescriptionForm()
    tag_form = TagForm()
    description_form.description.data = photo.description
    return render_template('main/photo.html', photo=photo, pagination=pagination, comments=comments,
                           description_form=description_form, tag_form=tag_form, comment_form=comment_form)


@main_bp.route('/photo/n/<int:photo_id>')
def photo_next(photo_id):
    photo = Photo.query.get_or_404(photo_id)
    photo_n = Photo.query.with_parent(photo.author).filter(Photo.id < photo_id).order_by(Photo.id.desc()).first()

    if photo_n is None:
        flash('This is already the last one.', 'info')
        return redirect(url_for('main.show_photo', photo_id=photo_id))
    return redirect(url_for('main.show_photo', photo_id=photo_n.id))


@main_bp.route('/photo/p/<int:photo_id>')
def photo_previous(photo_id):
    photo = Photo.query.get_or_404(photo_id)
    photo_p = Photo.query.with_parent(photo.author).filter(Photo.id > photo_id).order_by(Photo.id.desc()).first()

    if photo_p is None:
        flash('This is already the first one.', 'info')
        return redirect(url_for('main.show_photo', photo_id=photo_id))
    return redirect(url_for('main.show_photo', photo_id=photo_p.id))


@main_bp.route('/delete/photo/<int:photo_id>', methods=['POST'])
@login_required
def delete_photo(photo_id):
    photo = Photo.query.get_or_404(photo_id)
    if current_user != photo.author and not current_user.can('MODERATE'):
        abort(403)

    db.session.delete(photo)
    db.session.commit()
    flash('Photo deleted.', 'info')

    photo_n = Photo.query.with_parent(photo.author).filter(Photo.id < photo_id).order_by(Photo.id.desc()).first()
    if photo_n is None:
        photo_p = Photo.query.with_parent(photo.author).filter(Photo.id > photo_id).order_by(Photo.id.desc()).first()
        if photo_p is None:
            return redirect(url_for('user.index', username=photo.author.username))
        return redirect(url_for('main.show_photo', photo_id=photo_p.id))
    return redirect(url_for('main.show_photo', photo_id=photo_n.id))


@main_bp.route('/report/photo/<int:photo_id>', methods=['POST'])
@login_required
@confirm_required
def report_photo(photo_id):
    photo = Photo.query.get_or_404(photo_id)
    photo.flag += 1
    db.session.commit()
    flash('Photo reported.', 'success')
    return redirect(url_for('.show_photo', photo_id=photo.id))


@main_bp.route('/photo/<int:photo_id>/description', methods=['POST'])
@login_required
def edit_description(photo_id):
    photo = Photo.query.get_or_404(photo_id)
    if current_user != photo.author:
        abort(403)

    form = DescriptionForm()
    if form.validate_on_submit():
        photo.description = form.description.data
        db.session.commit()
        flash('Description updated.', 'success')
    flash_errors(form)
    return redirect(url_for('main.show_photo', photo_id=photo.id))


@main_bp.route('/photo/<int:photo_id>/tags', methods=['POST'])
@login_required
def new_tag(photo_id):
    photo = Photo.query.get_or_404(photo_id)
    if current_user != photo.author:
        abort(403)

    form = TagForm()
    if form.validate_on_submit():
        for name in form.tag.data.split():
            tag = Tag.query.filter(Tag.name == name).first()
            if tag is None:
                tag = Tag(name=name)
                db.session.add(tag)
            if tag not in photo.tags:
                photo.tags.append(tag)
                db.session.commit()
        flash('Tag added.', 'success')
    flash_errors(form)
    return redirect(url_for('main.show_photo', photo_id=photo.id))


@main_bp.route('/delete/tag/<int:photo_id>/<int:tag_id>', methods=['POST'])
@login_required
def delete_tag(photo_id, tag_id):
    photo = Photo.query.get_or_404(photo_id)
    tag = Tag.query.get_or_404(tag_id)
    if current_user != photo.author and not current_user.can('MODERATE'):
        abort(403)

    if tag in photo.tags:
        photo.tags.remove(tag)
        db.session.commit()
        flash('Tag deleted.', 'info')
        if tag.photos is None:
            db.session.delete(tag)
            db.session.commit()
    else:
        flash('Add this tag first.', 'warning')
    return redirect(url_for('main.show_photo', photo_id=photo_id))


@main_bp.route('/tag/<int:tag_id>', defaults={'order': 'by_time'})
@main_bp.route('/tag/<int:tag_id>/<order>')
def show_tag(tag_id, order):
    tag = Tag.query.get_or_404(tag_id)

    page = request.args.get('page', 1, type=int)
    per_page = current_app.config['APP_PHOTO_PER_PAGE']
    order_rule = 'time'
    pagination = Photo.query.with_parent(tag).order_by(Photo.timestamp.desc()).paginate(page, per_page)
    photos = pagination.items

    if order == 'by_collects':
        photos.sort(key=lambda x: len(x.collectors), reverse=True)
        order_rule = 'collects'
    return render_template('main/tag.html', tag=tag, pagination=pagination, photos=photos, order_rule=order_rule)


@main_bp.route('/photo/set-comment/<int:photo_id>', methods=['POST'])
@login_required
@permission_required('COMMENT')
def new_comment(photo_id):
    photo = Photo.query.get_or_404(photo_id)
    page = request.args.get('page', 1, type=int)

    form = CommentForm()
    if form.validate_on_submit():
        body = form.body.data
        comment = Comment(
            body=body,
            photo=photo,
            author=current_user._get_current_object()
        )
        replied_id = request.args.get('reply')
        if replied_id:
            comment.replied = Comment.query.get_or_404(replied_id)
        db.session.add(comment)
        db.session.commit()
        flash('Comment published.', 'success')
        if photo.author.receive_comment_notification and current_user != photo.author:
            push_comment_notification(photo_id=photo_id, receiver=photo.author, page=page)
    flash_errors(form)
    return redirect(url_for('main.show_photo', photo_id=photo_id, page=page))


@main_bp.route('/photo/set-comment/<int:photo_id>', methods=['POST'])
@login_required

app/memory_cache/templates/main/_comment.html
<div class="comments" id="comments">
    <h3>{{ pagination.total }} Comments
        <small>
            <a href="{{ url_for('main.show_photo', photo_id=photo.id, page=pagination.pages or 1) }}#comments">
                earliest
            </a>
        </small>
        {% if current_user == photo.author %}
            <form class="float-right" method="post"
                  action="{{ url_for('main.set_comment', photo_id=photo.id, next=request.full_path) }}">
                <input type="hidden" name="csrf_token" value="{{ csrf_token() }}">
                <button type="submit" class="btn btn-warning btn-sm">
                    {% if photo.can_comment %}Disabled{% else %}Enable{% endif %} Comment
                </button>
            </form>
        {% endif %}
    </h3>
    {% if comments %}
        {% for comment in comments %}
            <div class="comment">
                <div class="comment-thumbnail">
                    <a href="{{ url_for('user.index', username=comment.author.username) }}">
                        <img class="rounded img-fluid avatar-s profile-popover"
                             data-href="{{ url_for('ajax.get_profile', user_id=comment.author.id) }}"
                             src="{{ url_for('main.get_avatar', filename=comment.author.avatar_s) }}">
                    </a>
                </div>
                <div class="comment-body">
                    <h6>
                        <a class="profile-popover"
                           data-href="{{ url_for('ajax.get_profile', user_id=comment.author.id) }}"
                           href="{{ url_for('user.index', username=comment.author.username) }}">
                            {{ comment.author.name }}
                        </a>
                        {% if comment.author == photo.author %}
                            <span class="badge badge-light">Author</span>
                        {% endif %}
                        <small data-toggle="tooltip" data-placement="top" data-timestamp="{{ comment.timestamp }}"
                               data-delay="500">
                            {{ moment(comment.timestamp).fromNow(refresh=True) }}
                        </small>
                        {% if current_user.is_authenticated %}
                            <span class="float-right">
                                <span class="dropdown">
                                    <button class="btn btn-sm btn-light" type="button" id="dropdownMenuButton"
                                            data-toggle="dropdown"
                                            aria-haspopup="true" aria-expanded="false">
                                    <span class="oi oi-ellipses"></span>
                                    </button>
                                    <span class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                                        <a class="dropdown-item btn"
                                           href="{{ url_for('.reply_comment', comment_id=comment.id) }}">
                                            <span class="oi oi-comment-square"></span> Reply
                                        </a>
                                        {% if current_user == comment.author or current_user == photo.author or current_user.can('MODERATE') %}
                                            <a class="dropdown-item" data-toggle="modal" href="#!"
                                               data-href="{{ url_for('.delete_comment', comment_id=comment.id) }}"
                                               data-target="#confirm-delete">
                                                <span class="oi oi-trash" aria-hidden="true"></span> Delete
                                            </a>
                                        {% endif %}
                                        <form class="inline" method="post"
                                              action="{{ url_for('.report_comment', comment_id=comment.id) }}">
                                                <input type="hidden" name="csrf_token" value="{{ csrf_token() }}">
                                                <button type="submit" class="dropdown-item">
                                                    <span class="oi oi-warning" aria-hidden="true"></span> Report
                                                </button>
                                            </form>
                                    </span>
                                </span>
                            </span>
                        {% endif %}
                    </h6>
                    <p>
                        {% if comment.replied %}
                            Reply
                            <a href="{{ url_for('user.index', username=comment.replied.author.username) }}">{{ comment.replied.author.name }}</a>
                            :
                        {%- endif -%}
                        {{ comment.body }}
                    </p>
                </div>
            </div>
            <hr>
        {% endfor %}
    {% else %}
        <div class="tip mb-3"><h5>No comments.</h5></div>
    {% endif %}
</div>
{% if comments %}
    <div class="page-footer">
        {{ render_pagination(pagination, fragment='#comments') }}
    </div>
{% endif %}
{% if request.args.get('reply') %}
    <div class="alert alert-dark">
        Reply to <strong>{{ request.args.get('author') }}</strong>:
        <a class="float-right" href="{{ url_for('main.show_photo', photo_id=photo.id) }}">Cancel</a>
    </div>
{% endif %}
{% if photo.can_comment and current_user.is_authenticated %}
    <div id="comment-form">
        {{ render_form(comment_form, action=url_for('main.new_comment', photo_id=photo.id, reply=request.args.get('reply'))) }}
    </div>
{% elif photo.can_comment and not current_user.is_authenticated %}
    <div class="tip">
        <h5>Please <a href="{{ url_for('auth.login') }}">log in</a>.</h5>
    </div>
{% else %}
    <div class="tip">
        <h5>Comment disabled.</h5>
    </div>
{% endif %}

app/memory_cache/templates/main/_photo_sidebar.html
{% from 'macros.html' import follow_area with context %}

<nav aria-label="Page navigation">
    <ul class="pagination">
        <li class="page-item">
            <a class="page-link" href="{{ url_for('main.photo_previous', photo_id=photo.id) }}">&larr;Previous</a>
        </li>
        <li class="page-item">
            <a class="page-link" href="{{ url_for('main.photo_next', photo_id=photo.id) }}">Next&rarr;</a>
        </li>
    </ul>
</nav>
<div class="card bg-light mb-3 w-100 sidebar-card">
    <div class="card-body">
        <div class="row">
            <a href="{{ url_for('user.index', username=photo.author.username) }}">
                <img class="sidebar-avatar rounded avatar-m"
                     src="{{ url_for('main.get_avatar', filename=photo.author.avatar_m) }}">
            </a>
            <div class="sidebar-profile">
                <h6 class="card-title">
                    <a href="{{ url_for('user.index', username=photo.author.username) }}">{{ photo.author.name }}</a>
                </h6>
                <p class="card-subtitle mb-2 text-muted">{{ photo.author.username }}</p>
                {{ follow_area(photo.author) }}
            </div>
        </div>
    </div>
</div>
<div class="card bg-light mb-3 w-100">
    <div class="card-body">
        <div id="description">
            <p>
                {% if photo.description %}
                    {{ photo.description }}
                {% endif %}
                {% if current_user == photo.author %}
                    <a id="description-btn" href="#">
                        <small><span class="oi oi-pencil"></span>edit description</small>
                    </a>
                {% endif %}
            </p>
        </div>
        {% if current_user == photo.author %}
            <div id="description-form">
                <form action="{{ url_for('main.edit_description', photo_id=photo.id) }}" method="post">
                    {{ description_form.csrf_token }}
                    {{ render_field(description_form.description) }}
                    <a class="btn btn-link btn-sm" id="cancel-description">Cancel</a>
                    {{ render_field(description_form.submit, class="btn btn-success btn-sm") }}
                </form>
            </div>
        {% endif %}
        <div id="tags">
            <p>
                {% if photo.tags %}
                    {% for tag in photo.tags %}
                        <a class="badge badge-light"
                           href="{{ url_for('.show_tag', tag_id=tag.id) }}" target="_blank"><span
                                class="oi oi-tag"></span> {{ tag.name }}</a>
                    {% endfor %}
                {% endif %}
                {% if current_user == photo.author %}
                    <a id="tag-btn" href="#">
                        <small><span class="oi oi-pencil"></span>edit tags</small>
                    </a>
                {% endif %}
            </p>
        </div>
        {% if current_user == photo.author %}
            <div id="tag-form">
                <form action="{{ url_for('main.new_tag', photo_id=photo.id) }}" method="post">
                    {{ tag_form.csrf_token }}
                    {{ render_field(tag_form.tag) }}
                    <a class="btn btn-link btn-sm" id="cancel-tag">Cancel</a>
                    {{ render_field(tag_form.submit, class="btn btn-success btn-sm") }}
                </form>
                {% if photo.tags %}
                    <hr>
                    {% for tag in photo.tags %}
                        <a class="dead-link" href="#!"
                           data-href="{{ url_for('main.delete_tag', photo_id=photo.id, tag_id=tag.id) }}"
                           data-toggle="modal"
                           data-target="#confirm-delete" title="Delete tag">
                            <span class="badge badge-danger">
                                {{ tag.name }}<span class="oi oi-trash" aria-hidden="true"></span></span>
                        </a>
                    {% endfor %}
                {% endif %}
            </div>
        {% endif %}
        {% if current_user.is_authenticated %}
            {% if current_user.is_collecting(photo) %} <!-- 显示取消收藏表单 -->
                <form class="inline" method="post" action="{{ url_for('main.uncollect', photo_id=photo.id) }}">
                    <input type="hidden" name="csrf_token" value="{{ csrf_token() }}">
                    <button type="submit" class="btn btn-outline-secondary btn-sm">
                        <span class="oi oi-x"></span>Uncollect
                    </button>
                </form>
            {% else %} <!-- 显示收藏表单 -->
                <form class="inline" method="post" action="{{ url_for('main.collect', photo_id=photo.id) }}">
                    <input type="hidden" name="csrf_token" value="{{ csrf_token() }}">
                    <button type="submit" class="btn btn-outline-secondary btn-sm">
                        <span class="oi oi-star"></span>Collect
                    </button>
                </form>
            {% endif %}
            <a href="{{ url_for('main.show_collectors', photo_id=photo.id) }}">{{ photo.collectors|length }}
                collectors</a>
        {% else %} <!-- 对未登录用户显示的收藏表单 -->
            <form class="inline" method="post" action="{{ url_for('main.uncollect', photo_id=photo.id) }}">
                <input type="hidden" name="csrf_token" value="{{ csrf_token() }}">
                <button type="submit" class="btn btn-outline-secondary btn-sm">
                    <span class="oi oi-star"></span>Uncollect
                </button>
            </form>
        {% endif %}
    </div>
</div>

app/memory_cache/templates/main/_sidebar.html
<div class="card bg-light mb-3 w-100 sidebar-nav">
    <div class="card-body">
        <div class="row">
            <a href="{{ url_for('user.index', username=current_user.username) }}">
                <img class="rounded avatar-s" style="margin-left: 15px; position: absolute"
                     src="{{ url_for('main.get_avatar', filename=current_user.avatar_m) }}">
            </a>
            <div class="sidebar-nav-name">
                <h6 class="card-title"><a
                        href="{{ url_for('user.index', username=current_user.username) }}">{{ current_user.name }}</a>
                </h6>
                <p class="card-subtitle mb-2 text-muted">{{ current_user.username }}</p>
            </div>
        </div>
        <a class="card-link" href="{{ url_for('user.index', username=current_user.username) }}">
            <span class="oi oi-home"></span> My Photos
        </a><br>
        <a class="card-link" href="{{ url_for('user.show_collections', username=current_user.username) }}">
            <span class="oi oi-star"></span> My Collections
        </a>
    </div>
</div>
<div class="card w-100 bg-light mb-3">
    <div class="card-header">Hot tags</div>
    <div class="list-group">
        {% for tag in tags %}
            <a class="list-group-item" href="{{ url_for('main.show_tag', tag_id=tag.id) }}">
                {{ tag.name }}<span class="badge badge-pill">{{ tag.photos|length }}</span>
            </a>
        {% endfor %}
    </div>
</div>

app/memory_cache/templates/main/explore.html
{% extends 'base.html' %}
{% from 'macros.html' import photo_card with context %}

{% block title %}Explore{% endblock %}

{% block content %}
    <div class="row">
        <div class="col-md-12">
            {% for photo in photos %}
                {{ photo_card(photo) }}
            {% endfor %}
        </div>
    </div>
    <div class="text-center">
        <a class="btn btn-primary" href="{{ url_for('main.explore') }}">
            <span class="oi oi-loop-circular"></span> Change
        </a>
    </div>
{% endblock %}

app/memory_cache/templates/main/profile_popup.html
<div class="popup-card">
    <img class="rounded img-fluid avatar-s popup-avatar" src="{{ url_for('main.get_avatar', filename=user.avatar_m) }}">
    <div class="popup-profile">
        <h6>{{ user.name }}</h6>
        <p class="text-muted">{{ user.username }}
            {% if current_user.is_authenticated %}
                {% if current_user != user and current_user.is_followed_by(user) %}
                    {% if user.is_followed_by(current_user) %}
                        <span class="badge badge-light">Follow each other</span>
                    {% else %}
                        <span class="badge badge-light">Follows you</span>
                    {% endif %}
                {% endif %}
            {% endif %}
        </p>
    </div>
    <p class="card-text">
        <a href="{{ url_for('user.index', username=user.username) }}">
            <strong>{{ user.photos|length }}</strong>Photos</a>&nbsp;
        <a href="{{ url_for('user.show_followers', username=user.username) }}">
            <strong id="followers-count-{{ user.id }}"
                    data-href="{{ url_for('ajax.followers_count', user_id=user.id) }}">{{ user.followers.count() - 1 }}
            </strong>Followers</a>
    </p>
    <a href="{{ url_for('user.index', username=user.username) }}" class="btn btn-light btn-sm">Homepage</a>
    {% if current_user.is_authenticated %}
        {% if current_user != user %}
            <button data-id="{{ user.id }}" data-href="{{ url_for('ajax.unfollow', username=user.username) }}"
                    class="{% if not current_user.is_following(user) %}hide{% endif %} btn btn-dark btn-sm unfollow-btn">
                Unfollow
            </button>
            <button data-id="{{ user.id }}" data-href="{{ url_for('ajax.follow', username=user.username) }}"
                    class="{% if current_user.is_following(user) %}hide{% endif %} btn btn-primary btn-sm follow-btn">
                Follow
            </button>
        {% endif %}
    {% else %}
        <form class="inline" method="post" action="{{ url_for('user.follow', username=user.username) }}">
            <input type="hidden" name="csrf_token" value="{{ csrf_token() }}">
            <button type="submit" class="btn btn-primary btn-sm">
                Follow
            </button>
        </form>
    {% endif %}
</div>

app/memory_cache/templates/main/upload.html
{% extends 'base.html' %}

{% block title %}Upload{% endblock title %}

{% block styles %}
    {{ super() }}
    <link rel="stylesheet" href="{{ url_for('static', filename='css/dropzone.min.css') }}" type="text/css">
    {{ dropzone.style('margin: 20px 0; border: 2px dashed #0087F7; min-height: 400px;') }}
{% endblock styles %}

{% block content %}
    <div class="page-header">
        <h1>Upload</h1>
    </div>
    <div class="row">
        <div class="col-md-12">
            {{ dropzone.create(action='main.upload') }}
            <a class="btn btn-light float-right"
               href="{{ url_for('main.index', username=current_user.username) }}">Done</a>
        </div>
    </div>
{% endblock content %}

{% block scripts %}
    {{ super() }}
    <script src="{{ url_for('static', filename='js/dropzone.min.js') }}"></script>
    {{ dropzone.config() }}
{% endblock scripts %}