app/memory_cache/blueprints/admin.py
from flask import Blueprint, flash, render_template, request, current_app
from flask_login import login_required

from memory_cache.decorators import permission_required, admin_required
from memory_cache.models import User, Photo, Tag, Comment, Role
from memory_cache.utils import redirect_back
from memory_cache.extensions import db
from memory_cache.forms.admin import EditProfileAdminForm

admin_bp = Blueprint('admin', __name__)


@admin_bp.route('/')
@login_required
@permission_required('MODERATE')
def index():
    user_count = User.query.count()
    locked_user_count = User.query.filter_by(locked=True).count()
    blocked_user_count = User.query.filter_by(active=False).count()
    photo_count = Photo.query.count()
    reported_photo_count = Photo.query.filter(Photo.flag > 0).count()
    tag_count = Tag.query.count()
    comment_count = Comment.query.count()
    reported_comment_count = Comment.query.filter(Comment.flag > 0).count()
    return render_template('admin/index.html', user_count=user_count, locked_user_count=locked_user_count,
                           blocked_user_count=blocked_user_count, photo_count=photo_count,
                           reported_photo_count=reported_photo_count, tag_count=tag_count, comment_count=comment_count,
                           reported_comment_count=reported_comment_count)


@admin_bp.route('/manage/user')
@login_required
@permission_required('MODERATE')
def manage_user():
    filter_rule = request.args.get('filter', 'all')
    page = request.args.get('page', 1, type=int)
    per_page = current_app.config['APP_MANAGE_USER_PER_PAGE']
    administrator = Role.query.filter_by(name='Administrator').first()
    moderator = Role.query.filter_by(name='Moderator').first()

    if filter_rule == 'locked':
        filtered_users = User.query.filter_by(locked=True)
    elif filter_rule == 'blocked':
        filtered_users = User.query.filter_by(active=False)
    elif filter_rule == 'administrator':
        filtered_users = User.query.filter_by(role=administrator)
    elif filter_rule == 'moderator':
        filtered_users = User.query.filter_by(role=moderator)
    else:
        filtered_users = User.query

    pagination = filtered_users.order_by(User.member_since.desc()).paginate(page, per_page)
    users = pagination.items
    return render_template('admin/manage_user.html', pagination=pagination, users=users)


@admin_bp.route('/manage/photo', defaults={'order': 'by_flag'})
@admin_bp.route('/manage/photo/<order>')
@login_required
@permission_required('MODERATE')
def manage_photo(order):
    page = request.args.get('page', 1, type=int)
    per_page = current_app.config['APP_MANAGE_PHOTO_PER_PAGE']
    order_rule = 'flag'
    if order == 'by_time':
        pagination = Photo.query.order_by(Photo.timestamp.desc()).paginate(page, per_page)
        order_rule = 'time'
    else:
        pagination = Photo.query.order_by(Photo.flag.desc()).paginate(page, per_page)
    photos = pagination.items
    return render_template('admin/manage_photo.html', pagination=pagination, photos=photos, order_rule=order_rule)


@admin_bp.route('/manage/tag')
@login_required
@permission_required('MODERATE')
def manage_tag():
    page = request.args.get('page', 1, type=int)
    per_page = current_app.config['APP_MANAGE_TAG_PER_PAGE']
    pagination = Tag.query.order_by(Tag.id.desc()).paginate(page, per_page)
    tags = pagination.items
    return render_template('admin/manage_tag.html', pagination=pagination, tags=tags)


@admin_bp.route('/manage/comment', defaults={'order': 'by_flag'})
@admin_bp.route('/manage/comment/<order>')
@login_required
@permission_required('MODERATE')
def manage_comment(order):
    page = request.args.get('page', 1, type=int)
    per_page = current_app.config['APP_MANAGE_COMMENT_PER_PAGE']
    order_rule = 'flag'
    if order == 'by_time':
        pagination = Comment.query.order_by(Comment.timestamp.desc()).paginate(page, per_page)
        order_rule = 'time'
    else:
        pagination = Comment.query.order_by(Comment.flag.desc()).paginate(page, per_page)
    comments = pagination.items
    return render_template('admin/manage_comment.html', pagination=pagination, comments=comments, order_rule=order_rule)


@admin_bp.route('/delete/tag/<int:tag_id>', methods=['POST'])
@login_required
@permission_required('MODERATE')
def delete_tag(tag_id):
    tag = Tag.query.get_or_404(tag_id)
    db.session.delete(tag)
    db.session.commit()
    flash('Tag deleted.', 'info')
    return redirect_back()



@admin_bp.route('/lock/user/<int:user_id>', methods=['POST'])
@login_required
@permission_required('MODERATE')
def lock_user(user_id):
    user = User.query.get_or_404(user_id)
    user.lock()
    flash('Account locked.', 'info')
    return redirect_back()


@admin_bp.route('/unlock/user/<int:user_id>', methods=['POST'])
@login_required
@permission_required('MODERATE')
def unlock_user(user_id):
    user = User.query.get_or_404(user_id)
    user.unlock()
    flash('Account unlocked.', 'info')
    return redirect_back()


@admin_bp.route('/block/user/<int:user_id>', methods=['POST'])
@login_required
@permission_required('MODERATE')
def block_user(user_id):
    user = User.query.get_or_404(user_id)
    user.block()
    flash('Account blocked.', 'info')
    return redirect_back()


@admin_bp.route('/unblock/user/<int:user_id>', methods=['POST'])
@login_required
@permission_required('MODERATE')
def unblock_user(user_id):
    user = User.query.get_or_404(user_id)
    user.unblock()
    flash('Account unblocked.', 'info')
    return redirect_back()


@admin_bp.route('/profile/<int:user_id>', methods=['GET', 'POST'])
@admin_required
def edit_profile_admin(user_id):
    user = User.query.get_or_404(user_id)
    form = EditProfileAdminForm(user=user)

    if form.validate_on_submit():
        user.name = form.name.data
        user.username = form.username.data
        user.website = form.website.data
        user.bio = form.bio.data
        user.location = form.location.data
        user.email = form.email.data
        role = Role.query.get(form.role.data)
        if role.name == 'Locked':
            user.lock()
        user.role = role
        user.confirmed = form.confirmed.data
        user.active = form.active.data
        db.session.commit()
        flash('Profile updated.', 'success')
        return redirect_back()
    form.name.data = user.name
    form.username.data = user.username
    form.website.data = user.website
    form.bio.data = user.bio
    form.location.data = user.location
    form.email.data = user.email
    form.role.data = user.role.id
    form.confirmed.data = user.confirmed
    form.active.data = user.active
    return render_template('admin/edit_profile.html', form=form, user=user)

app/memory_cache/blueprints/main.py
import os

from flask import Blueprint, render_template, request, current_app, send_from_directory, flash, redirect, url_for, abort
from flask_dropzone import random_filename
from flask_login import current_user
from flask_login import login_required
from sqlalchemy.sql.expression import func

from memory_cache.decorators import permission_required, confirm_required
from memory_cache.extensions import db
from memory_cache.forms.main import DescriptionForm, TagForm, CommentForm
from memory_cache.models import Photo, Tag, Comment, Collect, Notification, Follow, User
from memory_cache.notifications import push_collect_notification, push_comment_notification
from memory_cache.utils import resize_image, flash_errors, redirect_back

main_bp = Blueprint('main', __name__)


@main_bp.route('/')
def index():
    if current_user.is_authenticated:
        tags = Tag.query.join(Tag.photos).group_by(Tag.id).order_by(func.count(Photo.id).desc()).limit(10)

        followed_photos = Photo.query.join(Follow, Follow.followed_id == Photo.author_id).filter(
            Follow.follower_id == current_user.id).order_by(Photo.timestamp.desc())
        page = request.args.get('page', 1, type=int)
        per_page = current_app.config['APP_PHOTO_PER_PAGE']
        pagination = followed_photos.paginate(page, per_page)
        photos = pagination.items
    else:
        pagination = None
        photos = None
        tags = None
    return render_template('main/index.html', pagination=pagination, photos=photos, tags=tags)


@main_bp.route('/explore')
def explore():
    photos = Photo.query.order_by(func.random()).limit(12)
    return render_template('main/explore.html', photos=photos)


@main_bp.route('/search')
def search():
    q =request.args.get('q', '')
    if q == '':
        flash('Enter keyword about photo, user or tag.', 'warning')
        return redirect_back()

    category = request.args.get('category', 'photo')
    page = request.args.get('page', 1, type=int)
    per_page = current_app.config['APP_SEARCH_RESULT_PER_PAGE']
    if category == 'photo':
        pagination = Photo.query.whooshee_search(q).paginate(page, per_page)
    elif category == 'tag':
        pagination = Tag.query.whooshee_search(q).paginate(page, per_page)
    else:
        pagination = User.query.whooshee_search(q).paginate(page, per_page)
    results = pagination.items
    return render_template('main/search.html', q=q, pagination=pagination, results=results, category=category)


@main_bp.route('/upload', methods=['GET', 'POST'])
@login_required
@confirm_required
@permission_required('UPLOAD')
def upload():
    if request.method == 'POST' and 'file' in request.files:
        f = request.files.get('file')
        filename = random_filename(f.filename)
        f.save(os.path.join(current_app.config['APP_UPLOAD_PATH'], filename))
        filename_s = resize_image(f, filename, 400)
        filename_m = resize_image(f, filename, 800)
        photo = Photo(
            filename=filename,
            filename_s=filename_s,
            filename_m=filename_m,
            author=current_user._get_current_object()
        )
        db.session.add(photo)
        db.session.commit()
    return render_template('main/upload.html')


@main_bp.route('/avatars/<path:filename>')
def get_avatar(filename):
    return send_from_directory(current_app.config['AVATARS_SAVE_PATH'], filename)


@main_bp.route('/uploads/<path:filename>')
def get_image(filename):
    return send_from_directory(current_app.config['APP_UPLOAD_PATH'], filename)


@main_bp.route('/photo/<int:photo_id>', methods=['GET', 'POST'])
def show_photo(photo_id):
    photo = Photo.query.get_or_404(photo_id)

    page = request.args.get('page', 1, type=int)
    per_page = current_app.config['APP_COMMENT_PER_PAGE']
    pagination = Comment.query.with_parent(photo).order_by(Comment.timestamp.desc()).paginate(page, per_page)
    comments = pagination.items

    comment_form = CommentForm()
    description_form = DescriptionForm()
    tag_form = TagForm()
    description_form.description.data = photo.description
    return render_template('main/photo.html', photo=photo, pagination=pagination, comments=comments,
                           description_form=description_form, tag_form=tag_form, comment_form=comment_form)


@main_bp.route('/photo/n/<int:photo_id>')
def photo_next(photo_id):
    photo = Photo.query.get_or_404(photo_id)
    photo_n = Photo.query.with_parent(photo.author).filter(Photo.id < photo_id).order_by(Photo.id.desc()).first()

    if photo_n is None:
        flash('This is already the last one.', 'info')
        return redirect(url_for('main.show_photo', photo_id=photo_id))
    return redirect(url_for('main.show_photo', photo_id=photo_n.id))


@main_bp.route('/photo/p/<int:photo_id>')
def photo_previous(photo_id):
    photo = Photo.query.get_or_404(photo_id)
    photo_p = Photo.query.with_parent(photo.author).filter(Photo.id > photo_id).order_by(Photo.id.desc()).first()

    if photo_p is None:
        flash('This is already the first one.', 'info')
        return redirect(url_for('main.show_photo', photo_id=photo_id))
    return redirect(url_for('main.show_photo', photo_id=photo_p.id))


@main_bp.route('/delete/photo/<int:photo_id>', methods=['POST'])
@login_required
def delete_photo(photo_id):
    photo = Photo.query.get_or_404(photo_id)
    if current_user != photo.author and not current_user.can('MODERATE'):
        abort(403)

    db.session.delete(photo)
    db.session.commit()
    flash('Photo deleted.', 'info')

    photo_n = Photo.query.with_parent(photo.author).filter(Photo.id < photo_id).order_by(Photo.id.desc()).first()
    if photo_n is None:
        photo_p = Photo.query.with_parent(photo.author).filter(Photo.id > photo_id).order_by(Photo.id.desc()).first()
        if photo_p is None:
            return redirect(url_for('user.index', username=photo.author.username))
        return redirect(url_for('main.show_photo', photo_id=photo_p.id))
    return redirect(url_for('main.show_photo', photo_id=photo_n.id))


@main_bp.route('/report/photo/<int:photo_id>', methods=['POST'])
@login_required
@confirm_required
def report_photo(photo_id):
    photo = Photo.query.get_or_404(photo_id)
    photo.flag += 1
    db.session.commit()
    flash('Photo reported.', 'success')
    return redirect(url_for('.show_photo', photo_id=photo.id))


@main_bp.route('/photo/<int:photo_id>/description', methods=['POST'])
@login_required
def edit_description(photo_id):
    photo = Photo.query.get_or_404(photo_id)
    if current_user != photo.author:
        abort(403)

    form = DescriptionForm()
    if form.validate_on_submit():
        photo.description = form.description.data
        db.session.commit()
        flash('Description updated.', 'success')
    flash_errors(form)
    return redirect(url_for('main.show_photo', photo_id=photo.id))


@main_bp.route('/photo/<int:photo_id>/tags', methods=['POST'])
@login_required
def new_tag(photo_id):
    photo = Photo.query.get_or_404(photo_id)
    if current_user != photo.author:
        abort(403)

    form = TagForm()
    if form.validate_on_submit():
        for name in form.tag.data.split():
            tag = Tag.query.filter(Tag.name == name).first()
            if tag is None:
                tag = Tag(name=name)
                db.session.add(tag)
            if tag not in photo.tags:
                photo.tags.append(tag)
                db.session.commit()
        flash('Tag added.', 'success')
    flash_errors(form)
    return redirect(url_for('main.show_photo', photo_id=photo.id))


@main_bp.route('/delete/tag/<int:photo_id>/<int:tag_id>', methods=['POST'])
@login_required
def delete_tag(photo_id, tag_id):
    photo = Photo.query.get_or_404(photo_id)
    tag = Tag.query.get_or_404(tag_id)
    if current_user != photo.author and not current_user.can('MODERATE'):
        abort(403)

    if tag in photo.tags:
        photo.tags.remove(tag)
        db.session.commit()
        flash('Tag deleted.', 'info')
        if tag.photos is None:
            db.session.delete(tag)
            db.session.commit()
    else:
        flash('Add this tag first.', 'warning')
    return redirect(url_for('main.show_photo', photo_id=photo_id))


@main_bp.route('/tag/<int:tag_id>', defaults={'order': 'by_time'})
@main_bp.route('/tag/<int:tag_id>/<order>')
def show_tag(tag_id, order):
    tag = Tag.query.get_or_404(tag_id)

    page = request.args.get('page', 1, type=int)
    per_page = current_app.config['APP_PHOTO_PER_PAGE']
    order_rule = 'time'
    pagination = Photo.query.with_parent(tag).order_by(Photo.timestamp.desc()).paginate(page, per_page)
    photos = pagination.items

    if order == 'by_collects':
        photos.sort(key=lambda x: len(x.collectors), reverse=True)
        order_rule = 'collects'
    return render_template('main/tag.html', tag=tag, pagination=pagination, photos=photos, order_rule=order_rule)


@main_bp.route('/photo/set-comment/<int:photo_id>', methods=['POST'])
@login_required
@permission_required('COMMENT')
def new_comment(photo_id):
    photo = Photo.query.get_or_404(photo_id)
    page = request.args.get('page', 1, type=int)

    form = CommentForm()
    if form.validate_on_submit():
        body = form.body.data
        comment = Comment(
            body=body,
            photo=photo,
            author=current_user._get_current_object()
        )
        replied_id = request.args.get('reply')
        if replied_id:
            comment.replied = Comment.query.get_or_404(replied_id)
        db.session.add(comment)
        db.session.commit()
        flash('Comment published.', 'success')
        if photo.author.receive_comment_notification and current_user != photo.author:
            push_comment_notification(photo_id=photo_id, receiver=photo.author, page=page)
    flash_errors(form)
    return redirect(url_for('main.show_photo', photo_id=photo_id, page=page))


@main_bp.route('/photo/set-comment/<int:photo_id>', methods=['POST'])
@login_required

app/memory_cache/templates/user/_header.html
{% from 'bootstrap/nav.html' import render_nav_itme %}
{% from 'macros.html' import follow_area with context %}

<div class="row">
    <div class="col-md-3">
        <img class="img-fluid rounded" src="{{ url_for('main.get_avatar', filename=user.avatar_l) }}">
    </div>
    <div class="col-md-9">
        <h1>{{ user.name }}
            <small class="text-muted">{{ user.username }}</small>
        </h1>
        {% if user.bio %}<p>{{ user.bio }}</p>{% endif %}
        <p>
            {% if user.website %}
                <span class="oi oi-link-intact"></span>
                <a href="{{ user.website }}">{{ user.website|truncate(30) }}</a>&nbsp;&nbsp;
            {% endif %}
            {% if user.location %}
                <span class="oi oi-map-marker"></span>
                <a href="https://www.google.com/maps?q={{ user.location }}">{{ user.location|truncate(20) }}</a>&nbsp;
                &nbsp;
            {% endif %}
            <span class="oi oi-calendar"></span>
            Joined {{ moment(user.member_since).format('LL') }}
        </p>
        <div>
            <div class="float-right">
                {{ follow_area(user) }}
            </div>
            {% if current_user != user %}
                {% if current_user.can('MODERATE') %}
                    {% if user.locked %}
                        <form class="inline" method="post" action="{{ url_for('admin.unlock_user', user_id=user.id) }}">
                            <input type="hidden" name="csrf_token" value="{{ csrf_token() }}">
                            <button class="btn btn-secondary btn-sm" type="submit">
                                Unlock
                            </button>
                        </form>
                    {% else %}
                        <form class="inline" method="post" action="{{ url_for('admin.lock_user', user_id=user.id) }}">
                            <input type="hidden" name="csrf_token" value="{{ csrf_token() }}">
                            <button class="btn btn-warning btn-sm" type="submit">
                                Lock
                            </button>
                        </form>
                    {% endif %}
                    {% if user.active %}
                        <form class="inline" method="post" action="{{ url_for('admin.block_user', user_id=user.id) }}">
                            <input type="hidden" name="csrf_token" value="{{ csrf_token() }}">
                            <button class="btn btn-warning btn-sm" type="submit">
                                Block
                            </button>
                        </form>
                    {% else %}
                        <form class="inline" method="post" action="{{ url_for('admin.unblock_user', user_id=user.id) }}">
                            <input type="hidden" name="csrf_token" value="{{ csrf_token() }}">
                            <button class="btn btn-secondary btn-sm" type="submit">
                                Unblock
                            </button>
                        </form>
                    {% endif %}
                    <a class="btn btn-light btn-sm" href="mailto:{{ user.email }}">Email</a>
                    {% if current_user.is_admin %}
                        <a class="btn btn-warning btn-sm"
                           href="{{ url_for('admin.edit_profile_admin', user_id=user.id) }}">Edit profile</a>
                    {% endif %}
                {% endif %}
            {% endif %}
        </div>
    </div>
</div>
<div class="user-nav">
    <ul class="nav nav-tabs">
        {{ render_nav_item('user.index', 'Photo', user.photos|length, use_li=True, username=user.username) }}
        {{ render_nav_item('user.show_collections', 'Collections', user.collections|length, use_li=True, username=user.username) }}
        {{ render_nav_item('user.show_followers', 'Followers', user.followers.count() - 1, use_li=True, username=user.username) }}
        {{ render_nav_item('user.show_following', 'Following', user.following.count() - 1, use_li=True, username=user.username) }}
    </ul>
</div>

app/memory_cache/templates/user/collections.html
{% extends 'base.html' %}
{% from 'bootstrap/pagination.html' import render_pagination %}
{% from 'macros.html' import photo_card %}

{% block title %}Collections{% endblock title %}

{% block content %}
    {% include 'user/_header.html' %}
    <div class="row">
        <div class="col-md-12">
            {% if collects %}
                {% if user.public_collections or current_user == user %}
                    {% for collect in collects %}
                        {{ photo_card(collect.collected) }}
                    {% endfor %}
                {% else %}
                    <div class="tip">
                        <h3>This user's collections was private.</h3>
                    </div>
                {% endif %}
            {% else %}
                <div class="tip text-center">
                    <h3>No collections.</h3>
                    {% if user == current_user %}
                        <a class="btn btn-link" href="{{ url_for('main.explore') }}">Explore</a>
                    {% endif %}
                </div>
            {% endif %}
        </div>
    </div>
    {% if collects %}
        <div class="page-footer">
            {{ render_pagination(pagination, align='center') }}
        </div>
    {% endif %}
{% endblock content %}

app/memory_cache/templates/user/followers.html
{% extends 'base.html' %}
{% from 'bootstrap/pagination.html' import render_pagination %}
{% from 'macros.html' import user_card with context %}

{% block title %}Followers{% endblock title %}

{% block content %}
    {% include 'user/_header.html' %}
    <div class="row">
        <div class="col-md-12">
            {% if follows|length != 1 %}
                {% for follow in follows %}
                    {% if current_user != follow.follower %}
                        {{ user_card(follow.follower) }}
                    {% endif %}
                {% endfor %}
            {% else %}
                <div class="tip text-center">
                    <h3>No followers.</h3>
                    {% if user == current_user %}
                        <a class="btn btn-link" href="{{ url_for('main.explore') }}">Explore</a>
                    {% endif %}
                </div>
            {% endif %}
        </div>
    </div>
    {% if collects %}
        <div class="page-footer">
            {{ render_pagination(pagination, align='center') }}
        </div>
    {% endif %}
{% endblock content %}

app/memory_cache/templates/user/following.html
{% extends 'base.html' %}
{% from 'bootstrap/pagination.html' import render_pagination %}
{% from 'macros.html' import user_card with context %}

{% block title %}Following{% endblock title %}

{% block content %}
    {% include 'user/_header.html' %}
    <div class="row">
        <div class="col-md-12">
            {% if follows|length != 1 %}
                {% for follow in follows %}
                    {% if current_user != follow.followed %}
                        {{ user_card(follow.followed) }}
                    {% endif %}
                {% endfor %}
            {% else %}
                <div class="tip text-center">
                    <h3>No following.</h3>
                    {% if user == current_user %}
                        <a class="btn btn-link" href="{{ url_for('main.explore') }}">Explore</a>
                    {% endif %}
                </div>
            {% endif %}
        </div>
    </div>
    {% if collects %}
        <div class="page-footer">
            {{ render_pagination(pagination, align='center') }}
        </div>
    {% endif %}
{% endblock content %}

app/memory_cache/templates/user/index.html
{% extends 'base.html' %}
{% from 'bootstrap/pagination.html' import render_pagination %}
{% from 'macros.html' import photo_card %}

{% block title %}{{ user.name }}{% endblock title %}

{% block content %}
    {% include 'user/_header.html' %}
    <div class="row">
        <div class="col-md-12">
            {% if photos %}
                {% for photo in photos %}
                    {{ photo_card(photo) }}
                {% endfor %}
            {% else %}
                <div class="tip text-center">
                    <h3>No photos.</h3>
                    {% if user == current_user %}
                        <a class="btn btn-link" href="{{ url_for('main.upload') }}">Upload</a>
                    {% else %}
                        <a class="btn btn-link" href="{{ url_for('main.explore') }}">Explore</a>
                    {% endif %}
                </div>
            {% endif %}
        </div>
    </div>
    {% if photos %}
        <div class="page-footer">
            {{ render_pagination(pagination, align='center') }}
        </div>
    {% endif %}
{% endblock content %}